name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # または master（あなたのデフォルトブランチ名に合わせてください）

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --if-present
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KENSYU10095 }}"
          channelId: live
          projectId: kensyu10095